/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.List;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Car;
import BusinessLogic.*;
import java.text.SimpleDateFormat;  
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;    
import static ui.MainJFrame.getTime;

/**
 *
 * @author sravyaganda
 */
public class SearchDetails extends javax.swing.JPanel {

    /**
     * Creates new form SearchDetails
     */
          private JPanel userProcessContainer;
    private CarsCatalog carsCatalog;
    public SearchDetails(JPanel userProcessContainer,CarsCatalog carsCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carsCatalog = carsCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        btnfirstcar = new javax.swing.JButton();
        btnavailablecars = new javax.swing.JButton();
        btnsearchcompany = new javax.swing.JButton();
        txtcompany = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        btnsearchyear = new javax.swing.JButton();
        txtserialnumber = new javax.swing.JTextField();
        btnSerialNumber = new javax.swing.JButton();
        txtmodelnumber = new javax.swing.JTextField();
        btnsearchmodel = new javax.swing.JButton();
        txtlocation = new javax.swing.JTextField();
        btnsearchlocation = new javax.swing.JButton();
        btnunavailable = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtminseat = new javax.swing.JTextField();
        txtmaxseat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtcertificate = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("                                        Search Car Details");

        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial Number", "Company", "Model", "Seat Capacity", "Available For Uber", "Location", "Maintenance Certificate Expiry Date"
            }
        ));
        tblCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCars);

        btnfirstcar.setText("First Available Car");
        btnfirstcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstcarActionPerformed(evt);
            }
        });

        btnavailablecars.setText("Available Cars");
        btnavailablecars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnavailablecarsActionPerformed(evt);
            }
        });

        btnsearchcompany.setText("Search By Company");
        btnsearchcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchcompanyActionPerformed(evt);
            }
        });

        btnsearchyear.setText("Search By Year");
        btnsearchyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchyearActionPerformed(evt);
            }
        });

        btnSerialNumber.setText("Search By SerialNumber");
        btnSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNumberActionPerformed(evt);
            }
        });

        btnsearchmodel.setText("Search By Model");
        btnsearchmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchmodelActionPerformed(evt);
            }
        });

        btnsearchlocation.setText("Search By Location");
        btnsearchlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchlocationActionPerformed(evt);
            }
        });

        btnunavailable.setText("Unavailable Cars");
        btnunavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunavailableActionPerformed(evt);
            }
        });

        jButton1.setText("Manufacturers");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Min Seat");

        jLabel3.setText("Max Seat");

        jButton2.setText("Search By Seats");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtcertificate.setText("Maintenance Certificate Expired Cars");
        txtcertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcertificateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnfirstcar)
                                .addGap(73, 73, 73)
                                .addComponent(btnavailablecars)
                                .addGap(72, 72, 72)
                                .addComponent(btnunavailable))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnsearchcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsearchyear, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSerialNumber))
                                .addGap(150, 150, 150)
                                .addComponent(jLabel2)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcertificate))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtminseat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(txtmaxseat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnsearchlocation))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtmodelnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnsearchmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(132, 132, 132)))))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfirstcar)
                    .addComponent(btnavailablecars)
                    .addComponent(btnunavailable)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcertificate))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearchcompany)
                    .addComponent(txtmodelnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearchmodel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsearchyear)
                            .addComponent(btnsearchlocation)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSerialNumber)
                    .addComponent(txtserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtminseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtmaxseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarsMouseClicked
        // TODO add your handling code here:
        //int selectedrow = tblCars.getSelectedRow();
    }//GEN-LAST:event_tblCarsMouseClicked

    private void btnfirstcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstcarActionPerformed
        // TODO add your handling code here:
        Car c= carsCatalog.getCarsCatalog().get(0);
         ArrayList<Car> list=new ArrayList<Car>();
         list.add(c);
        populateTable(list);
    }//GEN-LAST:event_btnfirstcarActionPerformed

    private void btnavailablecarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnavailablecarsActionPerformed
        // TODO add your handling code here:
        ArrayList<Car> list=new ArrayList<Car>();
        for(Car c:carsCatalog.getCarsCatalog())
        {
            if(c.getisStatusOfCar())
            {
                list.add(c);
            }
        }
        populateTable(list);
    }//GEN-LAST:event_btnavailablecarsActionPerformed

    private void btnsearchcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchcompanyActionPerformed
        // TODO add your handling code here:
            ArrayList<Car> list=new ArrayList<Car>();
            String companyname = txtcompany.getText();
        if(companyname==null || companyname.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Company Name to Search");
            return;
        }
        else
        {
           for(Car c:carsCatalog.getCarsCatalog())
        {
            if(c.getCompany().equals(companyname))
            {
                list.add(c);
            }
        }
        populateTable(list); 
        }
    }//GEN-LAST:event_btnsearchcompanyActionPerformed

    private void btnsearchyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchyearActionPerformed
        // TODO add your handling code here:
          ArrayList<Car> list=new ArrayList<Car>();
          try{
           int year = Integer.parseInt(txtyear.getText());}
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please input a valid number!");
            return;
        }
        
           for(Car c:carsCatalog.getCarsCatalog())
        {
            if(c.getYearOfManufacture()==Integer.parseInt(txtyear.getText()))
            {
                list.add(c);
            }
        }
        populateTable(list); 
        
    }//GEN-LAST:event_btnsearchyearActionPerformed

    private void btnSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNumberActionPerformed
        // TODO add your handling code here:
         ArrayList<Car> list=new ArrayList<Car>();
            String serialnumber = txtserialnumber.getText();
        if(serialnumber==null || serialnumber.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Serial Number to Search");
            return;
        }
        else
        {
           for(Car c:carsCatalog.getCarsCatalog())
        {
            if(c.getSerialno().equals(serialnumber))
            {
                list.add(c);
            }
        }
        populateTable(list); 
        }
    }//GEN-LAST:event_btnSerialNumberActionPerformed

    private void btnsearchmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchmodelActionPerformed
        // TODO add your handling code here:
           ArrayList<Car> list=new ArrayList<Car>();
            String model = txtmodelnumber.getText();
        if(model==null || model.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Model to Search");
            return;
        }
        else
        {
           for(Car c:carsCatalog.getCarsCatalog())
        {
            if(c.getModelNumber().equals(model))
            {
                list.add(c);
            }
        }
        populateTable(list); 
        }
    }//GEN-LAST:event_btnsearchmodelActionPerformed

    private void btnsearchlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchlocationActionPerformed
        // TODO add your handling code here:
         ArrayList<Car> list=new ArrayList<Car>();
            String location = txtlocation.getText();
        if(location==null || location.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Location to Search");
            return;
        }
        else
        {
           for(Car c:carsCatalog.getCarsCatalog())
        {
            if(c.getLocation().equals(location))
            {
                list.add(c);
            }
        }
        populateTable(list); 
        }
    }//GEN-LAST:event_btnsearchlocationActionPerformed

    private void btnunavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunavailableActionPerformed
        // TODO add your handling code here:
         ArrayList<Car> list=new ArrayList<Car>();
        for(Car c:carsCatalog.getCarsCatalog())
        {
            if(!c.getisStatusOfCar())
            {
                list.add(c);
            }
        }
        populateTable(list);
    }//GEN-LAST:event_btnunavailableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblCars.getModel();
    dtm.setRowCount(0);
   ArrayList<String> companyList = new ArrayList<String>(); 
for(Car c:carsCatalog.getCarsCatalog())
{
    companyList.add(c.getCompany());
}
HashSet<String> hset = new HashSet<String>(companyList);
    
    for(String c:hset){
        Object[] row = new Object[10];
            row[1]=c;
           
                 
        dtm.addRow(row);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
             ArrayList<Car> list=new ArrayList<Car>();
        try{
        int minseat=Integer.parseInt(txtminseat.getText());
        int maxseat=Integer.parseInt(txtmaxseat.getText());
        }
         catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter Both Min and Max Seat");
            return;
        }
        int minseat=Integer.parseInt(txtminseat.getText());
        int maxseat=Integer.parseInt(txtmaxseat.getText());
         for(Car c:carsCatalog.getCarsCatalog())
        {
            if((c.getSeatCapacity()>=minseat) &&( c.getSeatCapacity()<=maxseat))
            {
                list.add(c);
            }
        }
        populateTable(list);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcertificateActionPerformed
        // TODO add your handling code here:
//       
        try{   
//           
   DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
   LocalDateTime now = LocalDateTime.now();  
     Date currentDate=new SimpleDateFormat("yyyy-MM-dd").parse(dtf.format(now));
//        Date presentdate=new SimpleDateFormat("dd/MM/yyyy").parse(dtf.format(now));
        ArrayList<Car> list=new ArrayList<Car>();
        for(Car c:carsCatalog.getCarsCatalog())
        {
            if(c.getMaintainExpdate().before(currentDate))
            {
                list.add(c);
            }
        }
        populateTable(list);}
         catch(ParseException e)
      {
           System.out.println("Exception occured while parsing the date parameter" ); 
      }
         
    }//GEN-LAST:event_txtcertificateActionPerformed
SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
        public void populateTable(ArrayList<Car> carsCatalog){
     
          DefaultTableModel dtm = (DefaultTableModel) tblCars.getModel();
    dtm.setRowCount(0);
    for(Car c:carsCatalog){
        Object[] row = new Object[10];
            row[0] = c.getSerialno();
            row[1]=c.getCompany();
            row[2]=c.getModelNumber();
            row[3]=c.getSeatCapacity();
            if(c.getisStatusOfCar()){
                row[4]="Yes";
            }
            else{
                row[4]="No";
            }
            row[5]=c.getLocation();
            row[6]=formatter.format(c.getMaintainExpdate());
                 
        dtm.addRow(row);
    }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSerialNumber;
    private javax.swing.JButton btnavailablecars;
    private javax.swing.JButton btnfirstcar;
    private javax.swing.JButton btnsearchcompany;
    private javax.swing.JButton btnsearchlocation;
    private javax.swing.JButton btnsearchmodel;
    private javax.swing.JButton btnsearchyear;
    private javax.swing.JButton btnunavailable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCars;
    private javax.swing.JButton txtcertificate;
    private javax.swing.JTextField txtcompany;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtmaxseat;
    private javax.swing.JTextField txtminseat;
    private javax.swing.JTextField txtmodelnumber;
    private javax.swing.JTextField txtserialnumber;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
